name: dasturlash_darslari
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  rive: ^0.13.4
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  adaptive_theme: ^3.6.0
  easy_localization: ^3.0.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  page_transition: ^2.1.0
  cloud_firestore: ^4.17.5
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  lottie: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/lotties/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/RiveAssets/
    - assets/translations/


  fonts:
     - family: SF Pro Rounded
       fonts:
         - asset: assets/fonts/SfProRounded/SF-Pro-Rounded-Bold.otf
         - asset: assets/fonts/SfProRounded/SF-Pro-Rounded-Light.otf
         - asset: assets/fonts/SfProRounded/SF-Pro-Rounded-Medium.otf
         - asset: assets/fonts/SfProRounded/SF-Pro-Rounded-Regular.otf
         - asset: assets/fonts/SfProRounded/SF-Pro-Rounded-Semibold.otf
         - asset: assets/fonts/SfProRounded/SF-Pro-Rounded-Thin.otf
           style: italic
